### PR TITLE
fix: Fix umd build

### PR DESCRIPTION
**Pull request by asafshen**
## Related Issues

fixes https://github.com/descope/etc/issues/3140
## Description

imports broke due to addition of named import (see more context in https://github.com/rollup/rollup/issues/1044)

splited into 2 index files

### CODE REVIEW

**Comment by asafshen** [comment]
fixing test

**Review by nirgur — APPROVED** [review]

**Comment by meirwah** [comment]
@asafshen lint fails here

**Comment by asafshen** [comment]
> @asafshen lint fails here

I'm working on a fix

**Review by nirgur — APPROVED** [review]

**Comment by asafshen** [comment]
please wait with the merge

I also want to release this and want to sync with Shriki about that

**Comment by meirwah** [comment]
@asafshen whats the status ? don't we need to merge ASAP ? due to https://github.com/descope/etc/issues/3140#issuecomment-1610093950 ?

**Comment by asafshen** [comment]
> @asafshen whats the status ? don't we need to merge ASAP ? due to https://github.com/descope/etc/issues/3140#issuecomment-1610093950 ?

Pending discussion with Shriki 

We'll merge it today, in the meantime there is a workaround, I agree it is relatively urgent but it can wait an hour to communicate this

**Comment by asafshen** [comment]
web-sdk version 1.3.3 now working well FYI

**Pull request merged**
