### PR TITLE
fix: nested form inputs do not work

### PR DESCRIPTION
**Pull request by Bars92**
## Related Issues

fixes https://github.com/descope/etc/issues/6958

## Related PRs
https://github.com/descope/descope-js/issues/520

## Description
- fix nested form inputs do not work while supporting object form value
- added test case

### CODE REVIEW

**Review by tomerlichtash — APPROVED** [review]

**Comment by tomerlichtash** [comment]
@Bars92 Why am I not seeing the updated lockfile in the Files Changed tab?

**Comment by Bars92** [comment]
@tomerlichtash why do you need to see it? haven't changed anything in package file so i reverted the change

**Review by tomerlichtash — APPROVED** [review]

**Comment by nirgur** [comment]
We moved these files,
now it's under packages/sdks/web-component/...

Sorry for the inconvenience

**Comment by Bars92** [comment]
np @nirgur conflicts resolved automatically. is the deployment broken?

**Comment by nirgur** [comment]
> np @nirgur conflicts resolved automatically. is the deployment broken?

Yes, we do not have permission to change the Vercel projects

**Comment by nirgur** [comment]
> > np @nirgur conflicts resolved automatically. is the deployment broken?
> 
> Yes, we do not have permission to change the Vercel projects

Fixed

**Comment by Bars92** [comment]
@tomerlichtash you can re-approve

**Review by tomerlichtash — APPROVED** [review]

**Pull request merged**
