### PR TITLE
Prevent button submission on `Enter` when loading/disabled

### PR DESCRIPTION
**Pull request by tomerlichtash**
Fixes https://github.com/descope/etc/issues/3992

### CODE REVIEW

**Review by dorsha — APPROVED** [review]

**Comment by nirgur** [comment]
I think it will be better to handle it in the `descope-button` component 
and not as part of the `web-component` lib

WDYT?

**Comment by tomerlichtash** [comment]
> I think it will be better to handle it in the `descope-button` component
> and not as part of the `web-component` lib

Agreed. Do you want to leave the implementation on the `web-component` package as is, though?

**Comment by tomerlichtash** [comment]
@nirgur Added clickable mixin to handle this via the button component: https://github.com/descope/web-components-ui/pull/156

**Comment by nirgur** [comment]
@tomerlichtash is this PR still relevant?

**Comment by tomerlichtash** [comment]
> @tomerlichtash is this PR still relevant?

No, fixed with clickableMixin. Closing.

**Pull request closed without merging**
