### PR TITLE
feat: use base url for static content

### PR DESCRIPTION
**Pull request by nirgur**
## Related Issues

Fixes https://github.com/descope/etc/issues/6022

### CODE REVIEW

**Comment by orius123** [comment]
what about packages/libs/sdk-mixins/src/mixins/staticResourcesMixin/staticResourcesMixin.ts ?

**Review by dorsha — APPROVED** [review]

**Comment by dorsha** [comment]
@nirgur need to release all sdks.
Also check @orius123 comment.

**Comment by nirgur** [comment]
> what about packages/libs/sdk-mixins/src/mixins/staticResourcesMixin/staticResourcesMixin.ts ?

This is being used in the widgets
Do we want it also there?

**Comment by orius123** [comment]
I think we do

**Comment by dorsha** [comment]
Yes, should be also for widgets.

**Pull request merged**
